### ISSUE TITLE
Error when running with `DaskTaskRunner` and `shell_run_command.submit()`

### ISSUE THREAD

**Issue by yhshin11** [PrefectHQ/prefect-shell#31]
Hello all,

I'm running into an error that I'm having trouble debugging:
`TypeError: submit() got an unexpected keyword argument 'key'`

For context, I'm trying to run `shell_run_command.submit()` with `DaskTaskRunner` to run many shell scripts in parallel. The code below runs without issue if I don't use `DaskTaskRunner`. Am I missing something? I can't seem to gather anything useful from the call stack.

Environment setup:

```bash
mkvirtualenv prefect-shell-test
pip install prefect prefect-dask prefect-shell
python shell_flow.py
```

Library versions:

```
prefect==2.3.1
prefect-dask==0.1.2
prefect-shell==0.1.1
```

Minimal code to reproduce:

```python
from prefect import flow
from prefect_dask import DaskTaskRunner
from prefect_shell import shell_run_command

@flow(task_runner=DaskTaskRunner())
def example_shell_run_command_flow():
    return shell_run_command.submit(command="ls .", return_all=True)

if __name__ == '__main__':
    example_shell_run_command_flow()
```

Full output:

```
19:24:40.816 | INFO    | prefect.engine - Created flow run 'certain-anteater' for flow 'example-shell-run-command-flow'
19:24:40.816 | INFO    | prefect.task_runner.dask - Creating a new Dask cluster with `distributed.deploy.local.LocalCluster`
2022-09-05 19:24:42,107 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-worker-space/worker-q53qntpb', purging
19:24:42.183 | INFO    | prefect.task_runner.dask - The Dask dashboard is available at http://127.0.0.1:8787/status
19:24:42.315 | INFO    | Flow run 'certain-anteater' - Created task run 'shell_run_command-7398b6ba-0' for task 'shell_run_command'
2022-09-05 19:24:42,669 - distributed.client - ERROR -
Traceback (most recent call last):
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/client.py", line 1579, in _close
    await self.scheduler_comm.close()
asyncio.exceptions.CancelledError
19:24:42.672 | ERROR   | Flow run 'certain-anteater' - Crash detected! Execution was interrupted by an unexpected exception.
2022-09-05 19:24:42,701 - distributed.core - ERROR -
Traceback (most recent call last):
  File "/home/yhshin/miniconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/yhshin/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 231, in create_then_begin_flow_run
    state = await begin_flow_run(
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 367, in begin_flow_run
    terminal_state = await orchestrate_flow_run(
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 670, in __aexit__
    raise exc_details[1]
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 199, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 1338, in report_flow_run_crashes
    raise exc from None
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 1321, in report_flow_run_crashes
    yield
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 653, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 938, in create_task_run_then_submit
    await submit_task_run(
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 994, in submit_task_run
    future = await task_runner.submit(
TypeError: submit() got an unexpected keyword argument 'key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/utils.py", line 799, in wrapper
    return await func(*args, **kwargs)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/scheduler.py", line 4032, in add_worker
    await self.handle_worker(comm, address)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/scheduler.py", line 5194, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/core.py", line 822, in handle_stream
    msgs = await comm.read()
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError
2022-09-05 19:24:42,703 - distributed.core - ERROR -
Traceback (most recent call last):
  File "/home/yhshin/miniconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/yhshin/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 231, in create_then_begin_flow_run
    state = await begin_flow_run(
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 367, in begin_flow_run
    terminal_state = await orchestrate_flow_run(
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 670, in __aexit__
    raise exc_details[1]
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 199, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 1338, in report_flow_run_crashes
    raise exc from None
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 1321, in report_flow_run_crashes
    yield
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 653, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 938, in create_task_run_then_submit
    await submit_task_run(
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 994, in submit_task_run
    future = await task_runner.submit(
TypeError: submit() got an unexpected keyword argument 'key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/utils.py", line 799, in wrapper
    return await func(*args, **kwargs)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/scheduler.py", line 4032, in add_worker
    await self.handle_worker(comm, address)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/scheduler.py", line 5194, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/core.py", line 822, in handle_stream
    msgs = await comm.read()
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError
2022-09-05 19:24:42,703 - distributed.core - ERROR -
Traceback (most recent call last):
  File "/home/yhshin/miniconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/yhshin/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 231, in create_then_begin_flow_run
    state = await begin_flow_run(
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 367, in begin_flow_run
    terminal_state = await orchestrate_flow_run(
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 670, in __aexit__
    raise exc_details[1]
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 199, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 1338, in report_flow_run_crashes
    raise exc from None
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 1321, in report_flow_run_crashes
    yield
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 653, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 938, in create_task_run_then_submit
    await submit_task_run(
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 994, in submit_task_run
    future = await task_runner.submit(
TypeError: submit() got an unexpected keyword argument 'key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/utils.py", line 799, in wrapper
    return await func(*args, **kwargs)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/scheduler.py", line 4032, in add_worker
    await self.handle_worker(comm, address)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/scheduler.py", line 5194, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/core.py", line 822, in handle_stream
    msgs = await comm.read()
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError
2022-09-05 19:24:42,704 - distributed.core - ERROR -
Traceback (most recent call last):
  File "/home/yhshin/miniconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/yhshin/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 231, in create_then_begin_flow_run
    state = await begin_flow_run(
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 367, in begin_flow_run
    terminal_state = await orchestrate_flow_run(
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 670, in __aexit__
    raise exc_details[1]
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 199, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 1338, in report_flow_run_crashes
    raise exc from None
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 1321, in report_flow_run_crashes
    yield
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 653, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 938, in create_task_run_then_submit
    await submit_task_run(
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 994, in submit_task_run
    future = await task_runner.submit(
TypeError: submit() got an unexpected keyword argument 'key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/utils.py", line 799, in wrapper
    return await func(*args, **kwargs)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/scheduler.py", line 4032, in add_worker
    await self.handle_worker(comm, address)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/scheduler.py", line 5194, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/core.py", line 822, in handle_stream
    msgs = await comm.read()
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError
Traceback (most recent call last):
  File "/home/yhshin/workspace/prefect-shell-test/shell_flow.py", line 11, in <module>
    example_shell_run_command_flow()
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/flows.py", line 384, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 158, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/home/yhshin/miniconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/yhshin/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 231, in create_then_begin_flow_run
    state = await begin_flow_run(
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 367, in begin_flow_run
    terminal_state = await orchestrate_flow_run(
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 670, in __aexit__
    raise exc_details[1]
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 199, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 1338, in report_flow_run_crashes
    raise exc from None
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 1321, in report_flow_run_crashes
    yield
  File "/home/yhshin/miniconda3/lib/python3.9/contextlib.py", line 653, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 938, in create_task_run_then_submit
    await submit_task_run(
  File "/home/yhshin/.virtualenvs/prefect-shell-test/lib/python3.9/site-packages/prefect/engine.py", line 994, in submit_task_run
    future = await task_runner.submit(
TypeError: submit() got an unexpected keyword argument 'key'
2022-09-05 19:24:42,708 - distributed.nanny - ERROR - Worker process died unexpectedly
2022-09-05 19:24:42,708 - distributed.nanny - ERROR - Worker process died unexpectedly
2022-09-05 19:24:42,709 - distributed.nanny - ERROR - Worker process died unexpectedly
2022-09-05 19:24:42,727 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1219 exit status was already read will report exitcode 255
```

**Comment by desertaxle** [comment]
> In the meantime, I did notice the same error happening with `RayTaskRunner` in the latest `prefect-ray-0.1.4`. Are the issues related?

Yes, the root cause for that issue is the same. There is a [PR open in the `prefect-ray` repository](https://github.com/PrefectHQ/prefect-ray/pull/35) to the fix the issue. Once that is merged, we will cut a new release to resolve the issue.
