### ISSUE TITLE
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached

### ISSUE THREAD

**Issue by knl** [PrefectHQ/prefect-shell#78]
# Expectation / Proposal

When I run the following code:

```py
from prefect import flow
from prefect_shell import shell_run_command

@flow(retries=12, retry_delay_seconds=3600)
def eod_data(t: int = 0):
    date_id = 20230328 + t

    res = shell_run_command(
        command=f"~/bin/fetch_data.sh {date_id}",
        return_all=True,
        cwd="/home/prefect",
    )
    return res
```

I get the following output:

```
Downloading flow code from storage at None
02:12:14 PM
prefect.flow_runs

Created task run 'shell_run_command-0' for task 'shell_run_command'
02:12:46 PM
prefect.flow_runs

Executing 'shell_run_command-0' immediately...
02:12:46 PM
prefect.flow_runs

Encountered exception during execution:
Traceback (most recent call last):
  File "/data/anaconda3/envs/ams/lib/python3.7/site-packages/prefect/engine.py", line 1545, in orchestrate_task_run
    result = await call.aresult()
  File "/data/anaconda3/envs/ams/lib/python3.7/site-packages/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "/data/anaconda3/envs/ams/lib/python3.7/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "/data/anaconda3/envs/ams/lib/python3.7/site-packages/prefect_shell/commands.py", line 98, in shell_run_command
    shell_command, env=current_env, cwd=cwd
  File "/data/anaconda3/envs/ams/lib/python3.7/site-packages/anyio/_core/_subprocesses.py", line 135, in open_process
    start_new_session=start_new_session,
  File "/data/anaconda3/envs/ams/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 1112, in open_process
    start_new_session=start_new_session,
  File "/data/anaconda3/envs/ams/lib/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/data/anaconda3/envs/ams/lib/python3.7/asyncio/base_events.py", line 1544, in subprocess_exec
    bufsize, **kwargs)
  File "/data/anaconda3/envs/ams/lib/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/data/anaconda3/envs/ams/lib/python3.7/asyncio/unix_events.py", line 941, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
02:12:47 PM
shell_run_command-0
prefect.task_runs

Finished in state Failed('Task run encountered an exception: RuntimeError: Cannot add child handler, the child watcher does not have a loop attached\n')
```

This is with prefect 2.8.7 and prefect_shell 0.1.5. Unfortunately, I can't downgrade anymore to see if the issue stops showing up.

# Traceback / Example

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-shell/#contributing) a pull request to resolve this!

**Comment by knl** [comment]
Can confirm that the issue doesn't occur with prefect 2.8.6

**Comment by ahuang11** [comment]
Maybe you can try ShellOperation?

**Comment by knl** [comment]
@ahuang11 sorry for a late response, but I only now got a chance to use ShellOperation. Sadly, suffers from the same issue.

```
Traceback (most recent call last):
  File "/home/prefect/.local/lib/python3.7/site-packages/prefect/engine.py", line 1719, in orchestrate_task_run
    result = await call.aresult()
  File "/home/prefect/.local/lib/python3.7/site-packages/prefect/_internal/concurrency/calls.py", line 292, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/prefect/.local/lib/python3.7/site-packages/prefect/_internal/concurrency/calls.py", line 316, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "flows/producers/nse_eod_data.py", line 20, in fetch_data
    working_directory="/home/prefect",
  File "/home/prefect/.local/lib/python3.7/site-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
  File "/home/prefect/.local/lib/python3.7/site-packages/prefect/_internal/concurrency/calls.py", line 383, in __call__
    return self.result()
  File "/home/prefect/.local/lib/python3.7/site-packages/prefect/_internal/concurrency/calls.py", line 283, in result
    return self.future.result(timeout=timeout)
  File "/home/prefect/.local/lib/python3.7/site-packages/prefect/_internal/concurrency/calls.py", line 169, in result
    return self.__get_result()
  File "/data/anaconda3/envs/ams/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/prefect/.local/lib/python3.7/site-packages/prefect/_internal/concurrency/calls.py", line 346, in _run_async
    result = await coro
  File "/data/anaconda3/envs/ams/lib/python3.7/site-packages/prefect_shell/commands.py", line 389, in run
    async with open_process(**input_open_kwargs) as process:
  File "/data/anaconda3/envs/ams/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/home/prefect/.local/lib/python3.7/site-packages/prefect/utilities/processutils.py", line 202, in open_process
    process = await anyio.open_process(command, **kwargs)
  File "/data/anaconda3/envs/ams/lib/python3.7/site-packages/anyio/_core/_subprocesses.py", line 135, in open_process
    start_new_session=start_new_session,
  File "/data/anaconda3/envs/ams/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 1112, in open_process
    start_new_session=start_new_session,
  File "/data/anaconda3/envs/ams/lib/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/data/anaconda3/envs/ams/lib/python3.7/asyncio/base_events.py", line 1544, in subprocess_exec
    bufsize, **kwargs)
  File "/data/anaconda3/envs/ams/lib/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/data/anaconda3/envs/ams/lib/python3.7/asyncio/unix_events.py", line 941, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
```

**Comment by knl** [comment]
It could be that this is to blame: https://stackoverflow.com/questions/57629155/asyncio-function-works-when-called-from-script-but-not-from-flask-route, as I'm using python 3.7.
